# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chihu.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='chihu.proto',
  package='',
  serialized_pb=_b('\n\x0b\x63hihu.proto\"4\n\x08Response\x12\x17\n\x06status\x18\x01 \x02(\x0e\x32\x07.Status\x12\x0f\n\x07message\x18\x02 \x01(\x0c\"Y\n\x0bUserAccount\x12\x10\n\x08username\x18\x01 \x02(\t\x12\x10\n\x08password\x18\x02 \x02(\t\x12\r\n\x05\x65mail\x18\x03 \x02(\t\x12\x17\n\x06school\x18\x04 \x02(\x0e\x32\x07.School\"5\n\x04Meal\x12\x10\n\x08imageUrl\x18\x01 \x02(\t\x12\x0c\n\x04name\x18\x02 \x02(\t\x12\r\n\x05price\x18\x03 \x02(\x02\"3\n\x11MealAndNumberPair\x12\x0e\n\x06mealId\x18\x01 \x02(\t\x12\x0e\n\x06number\x18\x02 \x02(\x05\"8\n\x13RegisterUserRequest\x12!\n\x0buserAccount\x18\x01 \x02(\x0b\x32\x0c.UserAccount\"4\n\x11\x43heckNetIdRequest\x12\r\n\x05netid\x18\x01 \x02(\t\x12\x10\n\x08password\x18\x02 \x02(\t\"\x15\n\x13ViewCanteensRequest\"%\n\x10ViewMealsRequest\x12\x11\n\tcanteenId\x18\x01 \x02(\t\"i\n\x10MakeOrderRequest\x12\x11\n\tcanteenId\x18\x01 \x02(\t\x12.\n\x12mealAndNumberPairs\x18\x02 \x03(\x0b\x32\x12.MealAndNumberPair\x12\x12\n\ntotalPrice\x18\x03 \x02(\x02\"-\n\x1a\x43ustomerFinishOrderRequest\x12\x0f\n\x07orderId\x18\x01 \x02(\t\"=\n\x1a\x43ustomerCancelOrderRequest\x12\x0f\n\x07orderId\x18\x01 \x02(\t\x12\x0e\n\x06reason\x18\x02 \x02(\x0c*$\n\x06School\x12\x1a\n\x16Sun_Yat_San_University\x10\x01*\x1f\n\x06Status\x12\x0b\n\x07succeed\x10\x01\x12\x08\n\x04\x66\x61il\x10\x02')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

_SCHOOL = _descriptor.EnumDescriptor(
  name='School',
  full_name='School',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='Sun_Yat_San_University', index=0, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=659,
  serialized_end=695,
)
_sym_db.RegisterEnumDescriptor(_SCHOOL)

School = enum_type_wrapper.EnumTypeWrapper(_SCHOOL)
_STATUS = _descriptor.EnumDescriptor(
  name='Status',
  full_name='Status',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='succeed', index=0, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='fail', index=1, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=697,
  serialized_end=728,
)
_sym_db.RegisterEnumDescriptor(_STATUS)

Status = enum_type_wrapper.EnumTypeWrapper(_STATUS)
Sun_Yat_San_University = 1
succeed = 1
fail = 2



_RESPONSE = _descriptor.Descriptor(
  name='Response',
  full_name='Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='Response.status', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='message', full_name='Response.message', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=15,
  serialized_end=67,
)


_USERACCOUNT = _descriptor.Descriptor(
  name='UserAccount',
  full_name='UserAccount',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='username', full_name='UserAccount.username', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='password', full_name='UserAccount.password', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='email', full_name='UserAccount.email', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='school', full_name='UserAccount.school', index=3,
      number=4, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=69,
  serialized_end=158,
)


_MEAL = _descriptor.Descriptor(
  name='Meal',
  full_name='Meal',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='imageUrl', full_name='Meal.imageUrl', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='name', full_name='Meal.name', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='price', full_name='Meal.price', index=2,
      number=3, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=160,
  serialized_end=213,
)


_MEALANDNUMBERPAIR = _descriptor.Descriptor(
  name='MealAndNumberPair',
  full_name='MealAndNumberPair',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='mealId', full_name='MealAndNumberPair.mealId', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='number', full_name='MealAndNumberPair.number', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=215,
  serialized_end=266,
)


_REGISTERUSERREQUEST = _descriptor.Descriptor(
  name='RegisterUserRequest',
  full_name='RegisterUserRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='userAccount', full_name='RegisterUserRequest.userAccount', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=268,
  serialized_end=324,
)


_CHECKNETIDREQUEST = _descriptor.Descriptor(
  name='CheckNetIdRequest',
  full_name='CheckNetIdRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='netid', full_name='CheckNetIdRequest.netid', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='password', full_name='CheckNetIdRequest.password', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=326,
  serialized_end=378,
)


_VIEWCANTEENSREQUEST = _descriptor.Descriptor(
  name='ViewCanteensRequest',
  full_name='ViewCanteensRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=380,
  serialized_end=401,
)


_VIEWMEALSREQUEST = _descriptor.Descriptor(
  name='ViewMealsRequest',
  full_name='ViewMealsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='canteenId', full_name='ViewMealsRequest.canteenId', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=403,
  serialized_end=440,
)


_MAKEORDERREQUEST = _descriptor.Descriptor(
  name='MakeOrderRequest',
  full_name='MakeOrderRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='canteenId', full_name='MakeOrderRequest.canteenId', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='mealAndNumberPairs', full_name='MakeOrderRequest.mealAndNumberPairs', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='totalPrice', full_name='MakeOrderRequest.totalPrice', index=2,
      number=3, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=442,
  serialized_end=547,
)


_CUSTOMERFINISHORDERREQUEST = _descriptor.Descriptor(
  name='CustomerFinishOrderRequest',
  full_name='CustomerFinishOrderRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='orderId', full_name='CustomerFinishOrderRequest.orderId', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=549,
  serialized_end=594,
)


_CUSTOMERCANCELORDERREQUEST = _descriptor.Descriptor(
  name='CustomerCancelOrderRequest',
  full_name='CustomerCancelOrderRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='orderId', full_name='CustomerCancelOrderRequest.orderId', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='reason', full_name='CustomerCancelOrderRequest.reason', index=1,
      number=2, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=596,
  serialized_end=657,
)

_RESPONSE.fields_by_name['status'].enum_type = _STATUS
_USERACCOUNT.fields_by_name['school'].enum_type = _SCHOOL
_REGISTERUSERREQUEST.fields_by_name['userAccount'].message_type = _USERACCOUNT
_MAKEORDERREQUEST.fields_by_name['mealAndNumberPairs'].message_type = _MEALANDNUMBERPAIR
DESCRIPTOR.message_types_by_name['Response'] = _RESPONSE
DESCRIPTOR.message_types_by_name['UserAccount'] = _USERACCOUNT
DESCRIPTOR.message_types_by_name['Meal'] = _MEAL
DESCRIPTOR.message_types_by_name['MealAndNumberPair'] = _MEALANDNUMBERPAIR
DESCRIPTOR.message_types_by_name['RegisterUserRequest'] = _REGISTERUSERREQUEST
DESCRIPTOR.message_types_by_name['CheckNetIdRequest'] = _CHECKNETIDREQUEST
DESCRIPTOR.message_types_by_name['ViewCanteensRequest'] = _VIEWCANTEENSREQUEST
DESCRIPTOR.message_types_by_name['ViewMealsRequest'] = _VIEWMEALSREQUEST
DESCRIPTOR.message_types_by_name['MakeOrderRequest'] = _MAKEORDERREQUEST
DESCRIPTOR.message_types_by_name['CustomerFinishOrderRequest'] = _CUSTOMERFINISHORDERREQUEST
DESCRIPTOR.message_types_by_name['CustomerCancelOrderRequest'] = _CUSTOMERCANCELORDERREQUEST
DESCRIPTOR.enum_types_by_name['School'] = _SCHOOL
DESCRIPTOR.enum_types_by_name['Status'] = _STATUS

Response = _reflection.GeneratedProtocolMessageType('Response', (_message.Message,), dict(
  DESCRIPTOR = _RESPONSE,
  __module__ = 'chihu_pb2'
  # @@protoc_insertion_point(class_scope:Response)
  ))
_sym_db.RegisterMessage(Response)

UserAccount = _reflection.GeneratedProtocolMessageType('UserAccount', (_message.Message,), dict(
  DESCRIPTOR = _USERACCOUNT,
  __module__ = 'chihu_pb2'
  # @@protoc_insertion_point(class_scope:UserAccount)
  ))
_sym_db.RegisterMessage(UserAccount)

Meal = _reflection.GeneratedProtocolMessageType('Meal', (_message.Message,), dict(
  DESCRIPTOR = _MEAL,
  __module__ = 'chihu_pb2'
  # @@protoc_insertion_point(class_scope:Meal)
  ))
_sym_db.RegisterMessage(Meal)

MealAndNumberPair = _reflection.GeneratedProtocolMessageType('MealAndNumberPair', (_message.Message,), dict(
  DESCRIPTOR = _MEALANDNUMBERPAIR,
  __module__ = 'chihu_pb2'
  # @@protoc_insertion_point(class_scope:MealAndNumberPair)
  ))
_sym_db.RegisterMessage(MealAndNumberPair)

RegisterUserRequest = _reflection.GeneratedProtocolMessageType('RegisterUserRequest', (_message.Message,), dict(
  DESCRIPTOR = _REGISTERUSERREQUEST,
  __module__ = 'chihu_pb2'
  # @@protoc_insertion_point(class_scope:RegisterUserRequest)
  ))
_sym_db.RegisterMessage(RegisterUserRequest)

CheckNetIdRequest = _reflection.GeneratedProtocolMessageType('CheckNetIdRequest', (_message.Message,), dict(
  DESCRIPTOR = _CHECKNETIDREQUEST,
  __module__ = 'chihu_pb2'
  # @@protoc_insertion_point(class_scope:CheckNetIdRequest)
  ))
_sym_db.RegisterMessage(CheckNetIdRequest)

ViewCanteensRequest = _reflection.GeneratedProtocolMessageType('ViewCanteensRequest', (_message.Message,), dict(
  DESCRIPTOR = _VIEWCANTEENSREQUEST,
  __module__ = 'chihu_pb2'
  # @@protoc_insertion_point(class_scope:ViewCanteensRequest)
  ))
_sym_db.RegisterMessage(ViewCanteensRequest)

ViewMealsRequest = _reflection.GeneratedProtocolMessageType('ViewMealsRequest', (_message.Message,), dict(
  DESCRIPTOR = _VIEWMEALSREQUEST,
  __module__ = 'chihu_pb2'
  # @@protoc_insertion_point(class_scope:ViewMealsRequest)
  ))
_sym_db.RegisterMessage(ViewMealsRequest)

MakeOrderRequest = _reflection.GeneratedProtocolMessageType('MakeOrderRequest', (_message.Message,), dict(
  DESCRIPTOR = _MAKEORDERREQUEST,
  __module__ = 'chihu_pb2'
  # @@protoc_insertion_point(class_scope:MakeOrderRequest)
  ))
_sym_db.RegisterMessage(MakeOrderRequest)

CustomerFinishOrderRequest = _reflection.GeneratedProtocolMessageType('CustomerFinishOrderRequest', (_message.Message,), dict(
  DESCRIPTOR = _CUSTOMERFINISHORDERREQUEST,
  __module__ = 'chihu_pb2'
  # @@protoc_insertion_point(class_scope:CustomerFinishOrderRequest)
  ))
_sym_db.RegisterMessage(CustomerFinishOrderRequest)

CustomerCancelOrderRequest = _reflection.GeneratedProtocolMessageType('CustomerCancelOrderRequest', (_message.Message,), dict(
  DESCRIPTOR = _CUSTOMERCANCELORDERREQUEST,
  __module__ = 'chihu_pb2'
  # @@protoc_insertion_point(class_scope:CustomerCancelOrderRequest)
  ))
_sym_db.RegisterMessage(CustomerCancelOrderRequest)


# @@protoc_insertion_point(module_scope)
